### ISSUE TITLE
Scripts saved as behaviors but then not assigned

### ISSUE THREAD

**Issue by macMikey** [bwmilby/SvgIconTool#4]
I was about to add the search function and submit a PR, when I noticed that all of the scripts, while exported, were still in place. Then I checked the behaviors of each of those, and noticed that they were not assigned.

**Comment by bwmilby** [comment]
That is actually intentional.  ScriptTracker takes care of script import/export.  Having them reside in the stack means it is a single file plug-in.

**Comment by bwmilby** [comment]
Sync the scripts to import the changes into the stack.  PR should only include the stack if binary changes are needed.

**Comment by bwmilby** [comment]
Closing issue since the script exports are not actual behaviors but are used to track changes to scripts over time and allow inspection/editing in text editors outside of the IDE when using the ScriptTracker plugin.

**Comment by macMikey** [comment]
i have not used scriptTracker, so I may need an introduction to it.

**Comment by bwmilby** [comment]
Check out the repo here:
https://github.com/bwmilby/scriptTracker
It was written a bit after I created this stack (which is why this one had not made it to GitHub)
